my_app/catalog/views.py
from flask import request, jsonify, Blueprint, render_template, flash, redirect, abort
from my_app import ALLOWED_EXTENSIONS
from flask.helpers import url_for
from werkzeug.utils import secure_filename
from my_app import db, app, es, cache
from my_app.catalog.models import Product, Category
from sqlalchemy.orm.util import join
from my_app.catalog.models import ProductForm, CategoryForm, product_created, category_created
import os, boto3
from my_app import mail
from flask_mail import Message
from threading import Thread





#from functools import wraps

catalog = Blueprint('catalog', __name__)


def send_mail(message):
    with app.app_context():
        mail.send(message)


def allowed_file(filename):
    return '.' in filename and \
        filename.lower().rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


'''
prints "Welcome to the catalog home" on the index route 
'''
@catalog.route('/home')
@catalog.route('/')
def home():
    if request.headers.get("X-Requested-With") == "XMLHttpRequest":
        products = Product.query.all()
        app.logger.info('Home page with total of %d products' % len(products))
        return jsonify({
            'count' : len(products)
        })
    return render_template('home.html')

@cache.cached(timeout=120)
@catalog.route('/products')
@catalog.route('/products/<int:page>')
def products(page=1): 
    #products = Product.query.all() expensive to fetch all from we will paginate (depracted for now)
    products = Product.query.paginate(page, 10)
    #uncomment to debug
    # import pdb; pdb.set_trace()
    # res = {} 
    # for product in products: 
    #     res[product.id] = { 
    #         'name': product.name, 
    #         'price': product.price, 
    #         'category': product.category.name
    #     } 
    # return jsonify(res) 
    return render_template('products.html', products=products)

@cache.memoize(120)
@catalog.route('/product/<id>') 
def product(id): 
    product = Product.query.get_or_404(id)

    # product_key = 'product-%s' % product.id 
    # redis.set(product_key, product.name) 
    # redis.expire(product_key, 600) 
    return render_template('product.html', product=product)  

# @catalog.route('/recent-products') 
# def recent_products(): 
#     keys_alive = redis.keys('product-*') 
#     products = [redis.get(k).decode('utf-8') for k in keys_alive] 
#     return jsonify({'visited': products})
    
@catalog.route('/product-create', methods=['POST','GET']) 
def create_product():
    form = ProductForm()
    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        category = Category.query.get_or_404(
            form.category.data
        )
        image = request.files and request.files['image']
        filename = ''
        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            session = boto3.Session(
                aws_access_key_id=app.config['AWS_ACCESS_KEY'],
                aws_secret_access_key=app.config['AWS_SECRET_KEY']
            )
            s3 = session.resource('s3')
            bucket = s3.Bucket(app.config['AWS_BUCKET'])
            if bucket not in list(s3.buckets.all()):
                bucket = s3.create_bucket(
                    Bucket=app.config['AWS_BUCKET'],
                    CreateBucketConfiguration={
                        'LocationConstraint': 'us-east-1'
                    },
                )
            bucket.upload_fileobj(
                image, filename,
                ExtraArgs={'ACL': 'public-read'})
        product = Product(name, price, category, filename)
        db.session.add(product) 
        db.session.commit()
        product_created.send(app, product=product)
        flash(f'The product {name} has been created', 'success')
        return redirect(url_for('catalog.product', id=product.id))

    if form.errors:
        flash(form.errors, 'danger')

    return render_template('product-create.html', form=form)

@catalog.route('/product-search')
@catalog.route('/product-search/<int:page>')
def product_search(page=1):
    name = request.args.get('name')
    price = request.args.get('price')
    category = request.args.get('category')
    products = Product.query
    if name:
        products = products.filter(Product.name.like('%' + name + '%'))
    if price:
        products = products.filter(Product.price.like('%' + price + '%'))
    if category:
        products = products.select_from(join(Product, Category)).filter(Category.name.like('%' + category + '%'))
    return render_template('products.html', products=products.paginate(page,10))

@catalog.route('/product-search-es')
@catalog.route('/product-search-es/<int:page>')
def product_search_es(page=1):
    q = request.args.get('q')
    products = es.search(index="catalog", body={
        "query": {
            "query_string": {
            "query" : q
            }
        }
    })
    return products



@catalog.route('/category-create', methods=['POST','GET'])
def create_category(): 
    form = CategoryForm()
    if form.validate_on_submit():
        name = request.form.get('name') 
        category = Category(name) 
        db.session.add(category) 
        db.session.commit()
        message = Message(
            "New category added",
            recipients=['anderson.shemar17@gmail.com']
            )
        message.body = render_template(
            "category-create-email-text.html",
            category=category
            )

        #mail.send(message)
        #sending mail on thread
        t = Thread(target=send_mail, args=(message))
        t.start()
        category_created.send(app, category=category)
        flash(f'Category {name} created successfully', 'success')
        return redirect(url_for('catalog.category', id=category.id))
    
    if form.errors:
        flash(form.errors, 'danger')
    
    return render_template('category-create.html', form=form)  

@catalog.route('/categories')
@cache.cached(timeout=120)
def categories(): 
    categories = Category.query.all()
    category_count = len(categories)
    # res = {} 
    # for category in categories: 
    #     res[category.id] = { 
    #         'name': category.name 
    #     } 
        # for product in category.products: 
        #     res[category.id]['products'] = { 
        #         'id': product.id, 
        #         'name': product.name, 
        #         'price': product.price,
        #     }
    # return jsonify(res)
    if category_count <= 0:
        flash(f'There are {category_count} categories in database', 'warning')
    return render_template('categories.html',categories=categories) 

@cache.memoize(120)
@catalog.route('/category/<id>') 
def category(id): 
    category = Category.query.get_or_404(id) 
    return render_template('category.html', category=category)

@app.route('/debug-sentry')
def trigger_error():
    division_by_zero = 1 / 0

@app.errorhandler(404)
def page_not_found(e):
    app.logger.error(e)
    return render_template('404.html'), 404

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shemar Store</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('catalog.home') }}">Shemar Store</a>
        </div>
      </div>
    </div>
    <div class="container">
    </br>
    <div>
      {% for category, message in get_flashed_messages (with_categories=true) %}
        <div class="alert alert-{{ category }} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
        </div>
      {% endfor %}
    </div>
    {% block container %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block script%}
    {% endblock %}
  </body>
</html>

my_app/templates/categories.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad" >
        {% for category in categories %}
            <div class="well">
                <a href="{{ url_for('catalog.category', id=category.id) }}">
                <h2>{{ category.name }}</h2>
                </a>
            </div>
            
        {% endfor %}
    </div>
{% endblock %}

my_app/templates/category-create-email-html.html
<p>A new category has been added to the catalog.</p>
<p>The name of the category is <a href="{{ url_for('catalog.category',id=category.id, _external = True) }}">
<h2>{{ category.name }}</h2>
</a>.
</p>

my_app/templates/category-create-email-text.html
A new category has been added to the catalog.
The name of the category is {{ category.name }}.
Click on the URL below to access the same:
{{ url_for('catalog.category', id=category.id, _external = True) }}
This is an automated email. Do not reply to it.

my_app/templates/category-create.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <form method="POST" action="{{ url_for('catalog.create_category') }}" role="form">
        {{ form.csrf_token }}
        <div class="form-group">{{ form.name.label }}: {{ form.name() }}</div>
        <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}

my_app/templates/category.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <h2>{{ category.name }}</h2>
    <div>
      {% for product in category.products %}
        <h3>
          <a href="{{ url_for('catalog.product', id=product.id) }}">{{ product.name }}</a>
          <small>$ {{ product.price }}</small>
        </h3>
      {% endfor %}
    </div>
  </div>
{% endblock %}

my_app/templates/home.html
{% extends 'base.html' %} 
 
{% block container %} 
  <h1>{{ ('Welcome to the Catalog Home') }}</h1>
  <a href="{{ url_for('catalog.products') }}" id="catalog_link">Click here to see the catalog</a>
  <br/>
  <br/>

{% endblock %} 
 
{% block script %} 
<script> 
$(document).ready(function(){ 
  $.getJSON("/home", function(data) { 
    $('#catalog_link').append('<span class="badge">' + data.count 
       + '</span>'); 
  }); 
}); 


</script> 
{% endblock %} 

my_app/templates/product-create.html
{% extends 'home.html' %}
{% block container %}
    <div class="top-pad">
        <form class="form-horizontal"
            method="POST"
            action="{{ url_for('catalog.create_product') }}"
            role="form"
            enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="form-group"> {{ form.name.label }} : {{form.name() }}</div>
            <div class="form-group"> {{ form.price.label }} : {{form.price() }}</div>
            <div class="form-group"> {{ form.category.label }} : {{form.category() }}</div>
            <div class="form-group"> {{ form.image.label }} : {{ form.image(style='display:inline;') }}</div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
{% endblock %}

my_app/templates/product.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    <img src="{{ 'https://s3.us-east-1.amazonaws.com/' + config['AWS_BUCKET'] + '/' + product.image_path }}"/>
    <h1>{{ product.name }}<small> {{ product.category.name }}</small></h1>
    <h4>{{ product.company }}</h4>
    <h3>{{ product.price }}</h3>
  </div>
{% endblock %}

my_app/templates/products.html
{% extends 'home.html' %}

{% block container %}
  <div class="top-pad">
    {% for product in products.items %}
      <div class="well">
        <h2>
          <a href="{{ url_for('catalog.product', id=product.id) }}">{{ product.name }}</a>
          <small>$ {{ product.price }}</small>
        </h2>
      </div>
    {% endfor %}
    {% if products.has_prev %}
      <a href="{{ url_for(request.endpoint, page=products.prev_num) }}">
        {{"<< Previous Page"}}
      </a>
    {% else %}
      {{"<< No Previous Page"}}
    {% endif %} |
    {% if products.has_next %}
      <a href="{{ url_for(request.endpoint, page=products.next_num) }}">
        {{"Next Page >>"}}
      </a>
    {% else %}
      {{"No Next Page >>"}}
    {% endif %}
  </div>
{% endblock %}